services:
  postgres:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: geckode
      POSTGRES_PASSWORD: s3cr3ts
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build: ./auth-service
    environment:
      DATABASE_ULR: postgres://geckode:s3cr3ts@postgres:5432/auth_db
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  postgres_data: